version: '3.3'

services:

  PG_DATABASE:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: PG_USER
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: PG_DATABASE

  backend:
    image: ${APP}-backend
    environment: 
      PG_USER: PG_USER
      PG_DATABASE: PG_DATABASE
      PG_PASSWORD: ${PASSWORD}
    ports:
      - 5555:5555

  frontend:
    image: ${APP}-frontend

  proxy:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./src/nginx.generated.conf:/etc/nginx/nginx.conf
